name: CI

on: [push, pull_request]

jobs:
  test_build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Build
        run: |
          cp CI/ESS/.env production/.env
          npm ci
          npm run compile
